# Generated by Django 5.2.10 on 2026-03-06 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('can_admin_site', 'Can access city admin pages')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
