# Generated by Django 6.0.2 on 2026-02-22 18:38

from django.db import migrations

def create_site_admin_group(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")

    group, _ = Group.objects.get_or_create(name="site_admin")

    perm = Permission.objects.get(codename="can_admin_site")
    group.permissions.add(perm)

def delete_site_admin_group(apps, schema_editor):
    from django.contrib.auth.models import Group
    Group.objects.filter(name="site_admin").delete()

class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RunPython(create_site_admin_group, delete_site_admin_group),
    ]
