# Generated by Django 6.0.2 on 2026-02-22 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_create_site_admin_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('can_admin_site', 'Can access city admin pages')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
