# Generated by Django 5.2.10 on 2026-03-03 18:37

from django.db import migrations

# def create_forums(apps, schema_editor):
#     Forum = apps.get_model('forum', 'Forum')
    


class Migration(migrations.Migration):
    dependencies = [
        ('idea_forum', '0001_initial'),
        # ('common', '0001_initial.cpython-312.pyc'),
        ('forum', '0001_initial'),
    ]

    operations = [
        # migrations.RunPython(create_forums)
    ]
