# Generated by Django 5.2.10 on 2026-04-29 04:00

from django.db import migrations

def call_service(apps, schema_editor):
    from idea_forum.services.service_objs import GetOrCreateAutoModUser
    GetOrCreateAutoModUser.execute({})

class Migration(migrations.Migration):

    dependencies = [
        ('idea_forum', '0002_m_create_forum_containers'),
        ('users', '0001_initial')
    ]

    operations = [
        migrations.RunPython(call_service, reverse_code=migrations.RunPython.noop),
    ]
