# Generated by Django 5.2.10 on 2026-02-11 01:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(editable=False, max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.IntegerField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Phone numbers must be exactly 10 digits long and not contain additional characters.', regex='^\\d{10}$')])),
                ('email', models.CharField(max_length=50, unique=True)),
                ('user_type', models.CharField(choices=[('Resident', 'Resident'), ('City Admin', 'City Admin')], max_length=10)),
                ('account_creation', models.DateTimeField(auto_now_add=True)),
                ('account_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Suspended', 'Suspended'), ('Banned', 'Banned')], max_length=9)),
            ],
        ),
    ]
