# Generated by Django 4.2.28 on 2026-02-17 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_line', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('topic', models.CharField(choices=[('Art', 'Arts & Culture'), ('Bus', 'Business'), ('Child', 'Childcare & Youth Programs'), ('Construction', 'Construction'), ('Events', 'Community Events'), ('Gov', 'Local Government'), ('Health', 'Health & Community Services'), ('House', 'Housing & Development'), ('Parks', 'Parks & Green Spaces'), ('Plan', 'Urban Planning'), ('Safe', 'Public Safety'), ('Senior', 'Senior Services'), ('Transport', 'Transportation & Infrastructure'), ('Volunteer', 'Volunteering Opportunities')], default='general', max_length=12)),
                ('message', models.TextField()),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('read_status', models.BooleanField(default=False)),
                ('file_location', models.CharField(choices=[('Inbox', 'Inbox'), ('Art', 'Arts & Culture'), ('Bus', 'Business'), ('Child', 'Childcare & Youth Programs'), ('Construction', 'Construction'), ('Events', 'Community Events'), ('Gov', 'Local Government'), ('Health', 'Health & Community Services'), ('House', 'Housing & Development'), ('Parks', 'Parks & Green Spaces'), ('Plan', 'Urban Planning'), ('Safe', 'Public Safety'), ('Senior', 'Senior Services'), ('Transport', 'Transportation & Infrastructure'), ('Volunteer', 'Volunteering Opportunities')], default='Inbox', max_length=12)),
            ],
        ),
    ]
