# Generated by Django 5.2.10 on 2026-02-04 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_line', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=500)),
                ('time_stamp', models.DateTimeField()),
                ('read_status', models.BooleanField()),
            ],
        ),
    ]
