# Generated by Django 5.2.10 on 2026-06-10 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea_suggestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='file_location',
            field=models.CharField(choices=[('Inbox', 'Inbox'), ('Arts & Culture', 'Arts & Culture'), ('Business', 'Business'), ('Childcare & Youth Programs', 'Childcare & Youth Programs'), ('Construction', 'Construction'), ('Community Events', 'Community Events'), ('Local Government', 'Local Government'), ('Health & Community Services', 'Health & Community Services'), ('Housing & Dev', 'Housing & Development'), ('Parks & Green Spaces', 'Parks & Green Spaces'), ('Urban Planning', 'Urban Planning'), ('Public Safety', 'Public Safety'), ('Senior Services', 'Senior Services'), ('Transportation & Infrastructure', 'Transportation & Infrastructure'), ('Volunteering', 'Volunteering Opportunities')], default='Inbox', max_length=31),
        ),
        migrations.AlterField(
            model_name='idea',
            name='message',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='idea',
            name='topic',
            field=models.CharField(choices=[('Arts & Culture', 'Arts & Culture'), ('Business', 'Business'), ('Childcare & Youth Programs', 'Childcare & Youth Programs'), ('Construction', 'Construction'), ('Community Events', 'Community Events'), ('Local Government', 'Local Government'), ('Health & Community Services', 'Health & Community Services'), ('Housing & Dev', 'Housing & Development'), ('Parks & Green Spaces', 'Parks & Green Spaces'), ('Urban Planning', 'Urban Planning'), ('Public Safety', 'Public Safety'), ('Senior Services', 'Senior Services'), ('Transportation & Infrastructure', 'Transportation & Infrastructure'), ('Volunteering', 'Volunteering Opportunities')], max_length=31),
        ),
    ]
