
# Generated by Django 4.2.28 on 2026-02-17 20:52

from django.db import migrations, models
import django.db.models.deletion







class Migration(migrations.Migration):

    dependencies = [
        ('common', '__first__'),
        ('idea_suggestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='file_location',
<<<<<<< HEAD
            field=models.CharField(choices=[('Inbox', 'Inbox'), ('Art', 'Arts & Culture'), ('Bus', 'Business'), ('Child', 'Childcare & Youth Programs'), ('Construction', 'Construction'), ('Events', 'Community Events'), ('Gov', 'Local Government'), ('Health', 'Health & Community Services'), ('House', 'Housing & Development'), ('Parks', 'Parks & Green Spaces'), ('Plan', 'Urban Planning'), ('Safe', 'Public Safety'), ('Senior', 'Senior Services'), ('Transport', 'Transportation & Infrastructure'), ('Volunteer', 'Volunteering Opportunities')], default=1, max_length=12),
            preserve_default=False,
=======
            field=models.CharField(choices=[('Inbox', 'Inbox'), ('Art', 'Arts & Culture'), ('Bus', 'Business'), ('Child', 'Childcare & Youth Programs'), ('Construction', 'Construction'), ('Events', 'Community Events'), ('Gov', 'Local Government'), ('Health', 'Health & Community Services'), ('House', 'Housing & Development'), ('Parks', 'Parks & Green Spaces'), ('Plan', 'Urban Planning'), ('Safe', 'Public Safety'), ('Senior', 'Senior Services'), ('Transport', 'Transportation & Infrastructure'), ('Volunteer', 'Volunteering Opportunities')], default='Inbox', max_length=12),
>>>>>>> feature/idea_suggestion
        ),
        migrations.AddField(
            model_name='idea',
            name='resident',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ideas', to='common.user'),
        ),
        migrations.AddField(
            model_name='idea',
            name='topic',
<<<<<<< HEAD
            field=models.CharField(choices=[('Art', 'Arts & Culture'), ('Bus', 'Business'), ('Child', 'Childcare & Youth Programs'), ('Construction', 'Construction'), ('Events', 'Community Events'), ('Gov', 'Local Government'), ('Health', 'Health & Community Services'), ('House', 'Housing & Development'), ('Parks', 'Parks & Green Spaces'), ('Plan', 'Urban Planning'), ('Safe', 'Public Safety'), ('Senior', 'Senior Services'), ('Transport', 'Transportation & Infrastructure'), ('Volunteer', 'Volunteering Opportunities')], default=1, max_length=12),
            preserve_default=False,
=======
            field=models.CharField(choices=[('Art', 'Arts & Culture'), ('Bus', 'Business'), ('Child', 'Childcare & Youth Programs'), ('Construction', 'Construction'), ('Events', 'Community Events'), ('Gov', 'Local Government'), ('Health', 'Health & Community Services'), ('House', 'Housing & Development'), ('Parks', 'Parks & Green Spaces'), ('Plan', 'Urban Planning'), ('Safe', 'Public Safety'), ('Senior', 'Senior Services'), ('Transport', 'Transportation & Infrastructure'), ('Volunteer', 'Volunteering Opportunities')], default='general', max_length=12),
>>>>>>> feature/idea_suggestion
        ),
        migrations.AlterField(
            model_name='idea',
            name='message',
<<<<<<< HEAD
            field=models.CharField(max_length=1000),
=======
            field=models.TextField(),
>>>>>>> feature/idea_suggestion
        ),
        migrations.AlterField(
            model_name='idea',
            name='read_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='idea',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
