# Generated by Django 5.2.10 on 2026-03-09 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea_suggestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='ideas/'),
        ),
    ]
