# Generated by Django 4.2.28 on 2026-02-17 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idea_suggestion', '0002_idea_file_location_idea_resident_idea_topic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='resident',
        ),
    ]
