# Generated by Django 6.0.2 on 2026-02-22 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea_suggestion', '0002_idea_file_location_idea_resident_idea_topic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='resident',
        ),
        migrations.AlterField(
            model_name='idea',
            name='file_location',
            field=models.CharField(choices=[('Inbox', 'Inbox'), ('Art', 'Arts & Culture'), ('Bus', 'Business'), ('Child', 'Childcare & Youth Programs'), ('Construction', 'Construction'), ('Events', 'Community Events'), ('Gov', 'Local Government'), ('Health', 'Health & Community Services'), ('House', 'Housing & Development'), ('Parks', 'Parks & Green Spaces'), ('Plan', 'Urban Planning'), ('Safe', 'Public Safety'), ('Senior', 'Senior Services'), ('Transport', 'Transportation & Infrastructure'), ('Volunteer', 'Volunteering Opportunities')], default='Inbox', max_length=12),
        ),
        migrations.AlterField(
            model_name='idea',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='idea',
            name='topic',
            field=models.CharField(choices=[('Art', 'Arts & Culture'), ('Bus', 'Business'), ('Child', 'Childcare & Youth Programs'), ('Construction', 'Construction'), ('Events', 'Community Events'), ('Gov', 'Local Government'), ('Health', 'Health & Community Services'), ('House', 'Housing & Development'), ('Parks', 'Parks & Green Spaces'), ('Plan', 'Urban Planning'), ('Safe', 'Public Safety'), ('Senior', 'Senior Services'), ('Transport', 'Transportation & Infrastructure'), ('Volunteer', 'Volunteering Opportunities')], default='general', max_length=12),
        ),
    ]
