# Generated by Django 6.0.2 on 2026-03-04 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea_suggestion', '0003_remove_idea_resident_alter_idea_file_location_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='resident',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ideas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='idea',
            name='topic',
            field=models.CharField(choices=[('Art', 'Arts & Culture'), ('Bus', 'Business'), ('Child', 'Childcare & Youth Programs'), ('Construction', 'Construction'), ('Events', 'Community Events'), ('Gov', 'Local Government'), ('Health', 'Health & Community Services'), ('House', 'Housing & Development'), ('Parks', 'Parks & Green Spaces'), ('Plan', 'Urban Planning'), ('Safe', 'Public Safety'), ('Senior', 'Senior Services'), ('Transport', 'Transportation & Infrastructure'), ('Volunteer', 'Volunteering Opportunities')], max_length=12),
        ),
    ]
