from django.db import models
from common.choices import User_Type, USER_TYPE_MAX_LENGTH, Account_Status, ACCT_STATUS_MAX_LENGTH
from common.validators import phone_number_validator

# SHARED MODELS ACROSS ALL FEATURE GO HERE (E.G. Residents, CityAdmin)
# Create your models here... Classes/models represent tables in a DB
# Attributes = fields
# Primary keys are auto generated by Django

# class Name(models.Model):
class User(models.Model):
    # field_name = models.TypeOfField(optional_constraints = some_value)
    user_name = models.CharField(max_length = 50, 
                                 blank = False, 
                                 unique = True,
                                 editable = False)
    
    first_name = models.CharField(max_length = 50, 
                                  blank = False)
    
    last_name = models.CharField(max_length = 50, 
                                 blank = False)
    
    #phone_number = models.IntegerField(max_length = 10, 
    #                                   blank = False,
    #                                   unique = True,
    #                                   validators=[phone_number_validator])
    
    email = models.CharField(max_length = 50, 
                             unique = True)
    
    user_type = models.CharField(max_length = USER_TYPE_MAX_LENGTH, 
                                 choices = User_Type.choices,
                                 blank = False)
    
    account_creation = models.DateTimeField(auto_now_add = True)

    #account_status = models.CharField(max_length = ACCT_STATUS_MAX_LENGTH,
    #                                  choices = Account_Status)

