# Generated by Django 5.2.10 on 2026-06-04 00:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('icon', models.ImageField(upload_to='gamification/')),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PointRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_type', models.CharField(choices=[('Login', 'Login'), ('Suggestion', 'Suggestion'), ('Comment', 'Comment'), ('Like', 'Like'), ('Receive Like', 'Receive Like'), ('Vote Poll', 'Vote Poll'), ('Grand Total', 'Grand Total')], max_length=12, unique=True)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BadgeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.badge')),
                ('resident', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BadgeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_type', models.CharField(choices=[('Login', 'Login'), ('Suggestion', 'Suggestion'), ('Comment', 'Comment'), ('Like', 'Like'), ('Receive Like', 'Receive Like'), ('Vote Poll', 'Vote Poll'), ('Grand Total', 'Grand Total')], max_length=12, null=True)),
                ('point_threshold', models.IntegerField()),
                ('badge', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gamification.badge')),
            ],
        ),
        migrations.CreateModel(
            name='PointsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_type', models.CharField(choices=[('Login', 'Login'), ('Suggestion', 'Suggestion'), ('Comment', 'Comment'), ('Like', 'Like'), ('Receive Like', 'Receive Like'), ('Vote Poll', 'Vote Poll'), ('Grand Total', 'Grand Total')], max_length=12)),
                ('points_earned', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('resident', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='points_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_type', models.CharField(choices=[('Login', 'Login'), ('Suggestion', 'Suggestion'), ('Comment', 'Comment'), ('Like', 'Like'), ('Receive Like', 'Receive Like'), ('Vote Poll', 'Vote Poll'), ('Grand Total', 'Grand Total')], max_length=12)),
                ('total_points', models.IntegerField(default=0)),
                ('resident', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_points', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
