# Generated by Django 5.2.10 on 2026-06-02 23:51

from django.db import migrations
from gamification.game_choices import PointType

# Sets up badges and rules for gamification
def seed_gamification(apps, schema_editor):
    # Rules for how points are earned
    PointRule = apps.get_model('gamification', 'PointRule')

    PointRule.objects.get_or_create(
        point_type=PointType.LOGIN,
        defaults={"value": 1}
    )
    PointRule.objects.get_or_create(
        point_type=PointType.SUGGESTION,
        defaults={"value": 5}
    )
    PointRule.objects.get_or_create(
        point_type=PointType.COMMENT,
        defaults={"value": 5}
    )
    PointRule.objects.get_or_create(
        point_type=PointType.LIKE,
        defaults={"value": 1}
    )
    PointRule.objects.get_or_create(
        point_type=PointType.RECEIVE_LIKE,
        defaults={"value": 3}
    )
    PointRule.objects.get_or_create(
        point_type=PointType.VOTE_POLL,
        defaults={"value": 3}
    )


    # Badges that exist    
    Badge = apps.get_model('gamification', 'Badge')

    new_resident_badge, _ = Badge.objects.get_or_create(
        name = "New Resident",
        defaults = {
            "icon": "gamification/badge_icons/temp_badge.svg",
            "message": "Thank you for joining our community. Let's get to work!"
        }
    )
    brainstormer_badge, _ = Badge.objects.get_or_create(
        name = "Brainstormer",
        defaults = {
            "icon": "gamification/badge_icons/temp_badge.svg",
            "message": "You have started shaping conversations with your ideas. Keep it up!"
        }
    )
    idea_engine_badge, _ = Badge.objects.get_or_create(
        name = "Idea Engine",
        defaults = {
            "icon": "gamification/badge_icons/temp_badge.svg",
            "message": "Your suggestions keep bringing new ideas to the table"
        }
    )
    new_commenter_badge, _ = Badge.objects.get_or_create(
        name = "New Commenter",
        defaults = {
            "icon": "gamification/badge_icons/temp_badge.svg",
            "message": "Your voice brings fresh perspective to our discussions"
        }
    )
    discussion_veteran_badge, _ = Badge.objects.get_or_create(
        name = "Discussion Veteran",
        defaults = {
            "icon": "gamification/badge_icons/temp_badge.svg",
            "message": "We can always count on you for thoughtful input"
        }
    )


    # Rules for how badges are earned
    BadgeRule = apps.get_model('gamification', 'BadgeRule')

    BadgeRule.objects.get_or_create(
        badge = new_resident_badge,
        point_type = PointType.LOGIN,
        defaults = {
            "point_threshold": 1
        }
    )
    BadgeRule.objects.get_or_create(
        badge = brainstormer_badge,
        point_type = PointType.SUGGESTION,
        defaults = {
            "point_threshold": 15
        }
    )
    BadgeRule.objects.get_or_create(
        badge = idea_engine_badge,
        point_type = PointType.SUGGESTION,
        defaults = {
            "point_threshold": 75
        }
    )
    BadgeRule.objects.get_or_create(
        badge = new_commenter_badge,
        point_type = PointType.COMMENT,
        defaults = {
            "point_threshold": 15
        }
    )
    BadgeRule.objects.get_or_create(
        badge = discussion_veteran_badge,
        point_type = PointType.COMMENT,
        defaults = {
            "point_threshold": 75
        }
    )


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_gamification),
    ]
